---
# tasks file for cxx

- name: install c/c++
  become: yes
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items:
    - gcc
    - "{{ pkgs[ansible_os_family | lower] }}"
  when: ansible_os_family != 'Darwin'

- name: install cmake/conan/cplusnew
  pip: name={{ item }} state=present extra_args='--user'
  with_items:
    - cmake
    - conan
    - cplusnew
