---
# tasks file for roles/python

# - name: install python pip
#   become: yes
# #   action: >
# #     {{ ansible_pkg_mgr }} name={{ item }} state=present
# #   with_items:
# #     - "{{ pkgs[ansible_os_family | lower] }}"
# #   when: ansible_os_family != 'Darwin'
#   include_tasks: pip.yml
#   when: not pip_installed

- name: install virtualenvwrapper
  pip: name=virtualenvwrapper state=present extra_args='--user'
  environment:
    PATH: '/usr/local/bin:{{ ansible_env.PATH }}'

# does the pip module support the 'show' command?
- name: get virtualenvwrapper
  shell: pip show virtualenvwrapper | grep ^Location
  register: vew_info
  changed_when: false
  environment:
    PATH: '/usr/local/bin:{{ ansible_env.PATH }}'

- name: set VIRTUALENVWRAPPER_PYTHON
  lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    line: 'export VIRTUALENVWRAPPER_PYTHON={{ ansible_python_interpreter }}'

- name: source virtualenvwrapper.sh
  vars:
    vew_sh: "{{ vew_info.stdout.split()[1] | regex_replace('/lib/.*', '/bin') }}/virtualenvwrapper.sh"
  lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    line: '. {{ vew_sh | replace(ansible_env.HOME, "$HOME") }}'

# ms-python.python
