---
# tasks file for roles/javascript

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  args:
    warn: no
    creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'

# TODO: --lts=carbon/boron
- name: install node
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}'
  args:
    warn: no
  with_items: [ '{{ node_install_list }}' ]
  environment:
    NVM_DIR: '{{ ansible_env.HOME }}/.nvm'

# TODO: set default

- name: get the path of default node
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use --silent --lts && which node'
  args:
    warn: no
  changed_when: false
  register: nodes_info
  environment:
    NVM_DIR: '{{ ansible_env.HOME }}/.nvm'

- name: 'install JavaScript utilities: {{ util_install_list }}'
  vars:
    bin_dir: '{{ nodes_info.stdout | dirname }}'
  npm:
    name: '{{ item }}'
    global: yes
    state: present
    # registry: https://registry.npm.taobao.org
    executable: '{{ bin_dir }}/npm'
  with_items: '{{ util_install_list }}'
  environment:
    NVM_DIR: '{{ ansible_env.HOME }}/.nvm'
    PATH: '{{ bin_dir }}:{{ ansible_env.PATH }}'

# - name: 'install JavaScript utilities: {{ util_install_list }}'
#   npm:
#     name: '{{ item }}'
#     global: yes
#     state: present
#     # registry: https://registry.npm.taobao.org
#   # environment:
#   #   NVM_DIR: '{{ ansible_env.HOME }}/.nvm'
#     # PATH: '{{ bin_dir }}:{{ ansible_env.PATH }}'
#   with_items: '{{ util_install_list }}'
