---
# tasks file for common

- name: install apm bash completion
  homebrew:
    name: '{{ item }}-completion'
    state: present
  with_items:
    - apm-bash
    # - cargo
    # - django
    # - docker
    # - docker-compose
    # - docker-machine
    # - gem
    # - gradle
    # - grunt
    # - maven
    # - rustc
    # - spring

# - name: touch bash profiles
#   file:
#     path: '{{ ansible_env.HOME }}/{{ item }}'
#     state: touch
#   with_items:
#     - '.bashrc'
#     - '.bash_profile'

# - name: update .bashrc
#   lineinfile:
#     line: '{{ item }}'
#     dest: '{{ ansible_env.HOME }}/.bashrc'
#   with_items:
#     - 'export CLICOLOR=1'
#     - 'PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"'
#     - '[ -f $(brew --prefix)/etc/bash_completion ] && . $(brew --prefix)/etc/bash_completion'

# - name: update .bashrc
#   lineinfile:
#     line: 'source ~/.bashrc'
#     dest: '{{ ansible_env.HOME }}/.bash_profile'
