---
# tasks file for common

# - name: change default sh to bash
#   become: yes
#   file:
#     src: bash
#     path: /bin/sh
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Check to see if curl is already installed
#   command: "curl --version"
#   ignore_errors: true
#   changed_when: false
#   check_mode: no
#   register: curl_installed

# - name: install curl
#   become: '{{ pm_become }}'
#   action: >
#     {{ ansible_pkg_mgr }} name=curl state=present
#   when: not curl_installed

- name: 'install [git, curl]'
  become: '{{ pm_become }}'
  package: name={{ item }} state=present
  with_items:
    - git
    - curl

# - name: Check to see if pip is already installed
#   command: pip --version
#   # ignore_errors: true
#   changed_when: false
#   check_mode: no
#   # register: pip_installed
#   # FIXME
#   environment:
#     PATH: '/usr/local/bin:{{ ansible_env.PATH }}'

- name: add repo for vscode and atom
  include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: 'install {{ editor_list }}'
  become: '{{ pm_become }}'
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ editor_list }}'
  when: ansible_os_family != 'Darwin'
  retries: 3

- name: 'install {{ editor_list }}'
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items: '{{ editor_list }}'
  when: ansible_os_family == 'Darwin'
  retries: 3

- name: macOS init
  include_tasks: macos.yml
  when: ansible_os_family == 'Darwin'
