---
# tasks file for ruby

- name: install ruby
  become: '{{ pm_become }}'
  package:
    name: ruby
    state: present

- name: install bundler and jekyll
  become: '{{ pm_become }}'
  gem:
    name: '{{ item }}'
    state: present
    user_install: yes
  with_items:
    - bundler
    - jekyll
  retries: 3
