---
# tasks file for ruby

- name: install ruby
  become: '{{ pm_become }}'
  package:
    name: ruby
    state: present

- name: install ruby-dev
  become: '{{ pm_become }}'
  package:
    name: ruby-dev
    state: present
  when: ansible_os_family == 'Debian'

- name: install ruby-devel
  become: '{{ pm_become }}'
  package:
    name: ruby-devel
    state: present
  when: ansible_os_family == 'Redhat'

- name: install bundler and jekyll
  become: '{{ pm_become }}'
  gem:
    name: '{{ item }}'
    state: present
    user_install: no
    repository: https://gems.ruby-china.org/
  with_items:
    - bundler
    - jekyll
  retries: 3
